/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const computed: typeof import('vue').computed
  const defineStore: typeof import('pinia').defineStore
  const h: typeof import('vue').h
  const onMounted: typeof import('vue').onMounted
  const reactive: typeof import('vue').reactive
  const ref: typeof import('vue').ref
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const unref: typeof import('vue').unref
  const watch: typeof import('vue').watch
}
