/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditHostInfo: typeof import('./src/components/EditHostInfo.vue')['default']
    HostsEditor: typeof import('./src/components/Editor/HostsEditor.vue')['default']
    HostsView: typeof import('./src/components/HostsView.vue')['default']
    LeftPanel: typeof import('./src/components/LeftPanel/index.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemHostItem: typeof import('./src/components/LeftPanel/SystemHostItem.vue')['default']
  }
}

// For TSX support
declare global {
  const EditHostInfo: typeof import('./src/components/EditHostInfo.vue')['default']
  const HostsEditor: typeof import('./src/components/Editor/HostsEditor.vue')['default']
  const HostsView: typeof import('./src/components/HostsView.vue')['default']
  const LeftPanel: typeof import('./src/components/LeftPanel/index.vue')['default']
  const NavBar: typeof import('./src/components/NavBar.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NCheckbox: typeof import('naive-ui')['NCheckbox']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NRadio: typeof import('naive-ui')['NRadio']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSelect: typeof import('naive-ui')['NSelect']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SystemHostItem: typeof import('./src/components/LeftPanel/SystemHostItem.vue')['default']
}