// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScheme(arg1) {
  return window['go']['app']['App']['DeleteScheme'](arg1);
}

export function GetSchemes() {
  return window['go']['app']['App']['GetSchemes']();
}

export function GetSystemHosts() {
  return window['go']['app']['App']['GetSystemHosts']();
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveScheme(arg1) {
  return window['go']['app']['App']['SaveScheme'](arg1);
}
