// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export type SchemeType = 'local' | 'remote'

export type Scheme = {
  id: string
  name: string
  type: SchemeType
  content?: string
  url?: string
  enabled: boolean
  createdAt: string
  updatedAt: string
}

export type Config = {
  schemes: Scheme[]
  activeScheme: string
}

export function GetSchemes(): Promise<Scheme[]> {
  // @ts-ignore
  return window['go']['main']['App']['GetSchemes']()
}
export function SaveScheme(scheme: Scheme): Promise<void> {
  // @ts-ignore
  return window['go']['main']['App']['SaveScheme'](scheme)
}
export function DeleteScheme(id: string): Promise<void> {
  // @ts-ignore
  return window['go']['main']['App']['DeleteScheme'](id)
}

export function GetSystemHosts(): Promise<string> {
  // @ts-ignore
  return window['go']['main']['App']['GetSystemHosts']()
}

export function LoadConfig(): Promise<Config> {
  // @ts-ignore
  return window['go']['main']['App']['LoadConfig']()
}
export function SaveConfig(cfg: Config): Promise<void> {
  // @ts-ignore
  return window['go']['main']['App']['SaveConfig'](cfg)
}