// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScheme(arg1) {
  return window['go']['main']['App']['DeleteScheme'](arg1);
}

export function GetEnv() {
  return window['go']['main']['App']['GetEnv']();
}

export function GetSchemes() {
  return window['go']['main']['App']['GetSchemes']();
}

export function GetSystemHosts() {
  return window['go']['main']['App']['GetSystemHosts']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveScheme(arg1) {
  return window['go']['main']['App']['SaveScheme'](arg1);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}
