// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';
import {config} from '../models';

export function DeleteScheme(arg1:string):Promise<void>;

export function GetEnv():Promise<runtime.EnvironmentInfo>;

export function GetSchemes():Promise<Array<config.Scheme>>;

export function GetSystemHosts():Promise<string>;

export function LoadConfig():Promise<config.Config>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveScheme(arg1:config.Scheme):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;
