// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT


export type Scheme = {
  id: string
  name: string
  hosts: Host[]
}
export function GetSchemes()
export function SaveScheme()
export function editScheme(schem: Scheme)
export function DeleteScheme(id: string)
export function GetSystemHosts()